apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../monitoring
  - ../vdu-bridge
  - ../whereabouts/crds
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - namespace.yaml
  #- gitrepo.yaml
  - daemonsets.yaml
  - netattach.yaml
  - nad.yaml
  - configmap.yaml  
 # - pod-monitor.yaml
 # - flux-dashboard-permanent.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: flux-control-plane-dashboard
    namespace: monitoring
    files:
      - flux-dashboard.json
    options:
      labels:
        grafana_dashboard: "1"