apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: workload-repo-source
  namespace: flux-system
spec:
  interval: 5m
  url: ssh://git@github.com/dnjasper/seshat-workload-platform.git 
  ref:
    branch: main
  secretRef:
    name: flux-git-deploy
   # name: flux-system