apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: multus-cni
  namespace: flux-system
spec:
  interval: 1m
  path: ../apps/multus-cni
  prune: true
  sourceRef:
    kind: GitRepository
    name: seshat-multus-platform-source
   # name: flux-system
  
  # targetNamespace: flux-system
  # decryption:
  #   provider: sops
  #   secretRef:
  #     name: sops-age
  








# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# resources:
# - ../multus-cni
# - gotk-components.yaml
# - gotk-sync.yaml
