apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: upf-app-delivery
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/upf
  prune: true
  sourceRef:
    kind: GitRepository
    name: workload-repo-source
